import type { Level } from "../types";

// ============================================================ CHAPTER 1 — THE PANTRY (Variables)

export const CH1: Level[] = [
  {
    id: "1.1",
    chapter: 1,
    title: "Label the Jars",
    concept: "Creating variables",
    points: 20,
    scene: "pantry",
    runLabel: "Day",
    story:
      "Pyu's pantry jars have lost their labels! Pyu only ever uses a jar with a clear label, so right now he can't cook a thing. You are Byte, Pyu's helper. You write the recipes, and Pyu follows them exactly, line by line.",
    goal: "Put two labelled jars on the shelf: a jar called `rice` holding the number **5**, and a jar called `name` holding the text **Pyu**.",
    notes: ["Press **Cook** and watch the shelf: each jar appears at the moment its line runs."],
    starterCode:
      "# Byte's first recipe for Pyu.\n# Each line is one step. Pyu follows the steps in order, top to bottom.\n\n",
    customers: [{ name: "Day 1" }],
    checks: [
      { type: "noError" },
      { type: "var", name: "rice", equals: 5, pyType: "int",
        whenValue: [{ value: "5", message: "The rice jar holds the text \"5\" (in quotes). Pyu needs the actual number 5, so leave the quotes off." }] },
      { type: "var", name: "name", equals: "Pyu", pyType: "str" },
    ],
    hints: [
      "In Python a jar is called a variable. You make one by writing its label, then an equals sign, then what goes inside.",
      "Numbers are written just as they are. Text has to be wrapped in quote marks. Without them, Python thinks it's the label of another jar.",
      "You need exactly two steps, one per jar. Labels are case-sensitive, so the jar must be called rice (all lowercase), not Rice.",
    ],
    successText: "Two jars labelled and on the shelf",
  },
  {
    id: "1.2",
    chapter: 1,
    title: "More Jars",
    concept: "Assignment",
    points: 20,
    scene: "pantry",
    runLabel: "Day",
    story:
      "Pyu drew a picture of how the pantry should look. He wants the shelf to match it exactly before the lunch rush.",
    goal: "Make four jars that match Pyu's picture: `eggs` (how many eggs), `sugar` (how many cups of sugar), `chef` (the name on the apron) and `oven_on` (whether the oven is on).",
    picture: [
      { emoji: "🥚", label: "A carton with 6 eggs" },
      { emoji: "🥣", label: "2 cups of sugar" },
      { emoji: "🧑‍🍳", label: "The apron says: Pyu" },
      { emoji: "🔥", label: "The oven light is ON" },
    ],
    notes: ["In Python, a yes/no answer is written True or False: capital first letter, no quotes."],
    starterCode: "# Make the shelf match Pyu's picture.\n\n",
    bindings: [{ object: "oven", variable: "oven_on" }],
    customers: [{ name: "Day 1" }],
    checks: [
      { type: "noError" },
      { type: "var", name: "eggs", equals: 6, pyType: "int" },
      { type: "var", name: "sugar", equals: 2, pyType: "int" },
      { type: "var", name: "chef", equals: "Pyu", pyType: "str" },
      { type: "var", name: "oven_on", equals: true, pyType: "bool",
        whenValue: [
          { value: "True", message: "oven_on holds the text \"True\" in quotes. Pyu needs Python's real yes value, True, with no quotes." },
          { value: "ON", message: "oven_on holds the text \"ON\". Pyu needs one of Python's two yes/no values instead." },
        ] },
    ],
    hints: [
      "Look at each picture card. The question tells you the jar's name, and the picture tells you what goes inside.",
      "Whole numbers need no quotes. The chef's name is text, so it does need quotes.",
      "The oven question is a yes or no. Python's yes is True, a special value rather than text, so it has no quote marks.",
    ],
    successText: "The pantry matches Pyu's picture",
  },
  {
    id: "1.3",
    chapter: 1,
    title: "Bad Labels",
    concept: "Naming rules",
    points: 20,
    scene: "pantry",
    runLabel: "Day",
    story:
      "Pyu wrote some labels in a hurry. Python has strict rules about labels, so it won't even start reading this recipe.",
    goal: "Python refuses to read three of Pyu's labels. Rename those jars so Python accepts them, but keep what's inside each jar exactly the same. Keep the announcement at the end too.",
    notes: ["Python only shows one problem at a time. Fix it, cook again, and read the next alarm."],
    starterCode:
      "# Pyu wrote these labels in a hurry. Python can't read them!\n2eggs = 12\nmy rice = 5\nclass = \"Pyu\"\nprint(\"Pantry labels fixed!\")\n",
    customers: [{ name: "Day 1" }],
    checks: [
      { type: "compiles" },
      { type: "noError" },
      { type: "hasValue", value: 12, pyType: "int", fail: "Pyu can't find a jar holding 12 eggs any more. Rename the jar, but keep 12 inside it." },
      { type: "hasValue", value: 5, pyType: "int", fail: "Pyu can't find a jar holding 5 scoops of rice any more. Rename the jar, but keep 5 inside it." },
      { type: "hasValue", value: "Pyu", pyType: "str", fail: "Pyu can't find a jar holding his name, \"Pyu\". Rename the jar, but keep the text inside it the same." },
      { type: "output", lines: ["Pantry labels fixed!"] },
    ],
    hints: [
      "Press Cook and read which line Pyu gets stuck on. Fix one label at a time.",
      "A label can't start with a digit, and it can't contain a space. Many Python cooks join words with an underscore _.",
      "Some words, like class, if and for, belong to Python itself and can't be used as labels. Pick a different word for the chef's jar.",
    ],
    successText: "Every label is one Python can read",
  },
  {
    id: "1.4",
    chapter: 1,
    title: "Refill",
    concept: "Reassignment",
    points: 20,
    scene: "pantry",
    runLabel: "Day",
    mode: "fill",
    story:
      "Every morning a delivery van brings more rice. The amounts are different every day, so Pyu needs a step that works on any day.",
    goal: "Tip today's delivery into the rice jar, so `rice` holds its **old amount plus the delivery**. The jars `rice` and `delivery` are already on the shelf, and their amounts change every day.",
    notes: ["Fill in the blank. Pyu will test your step on three different days."],
    fillTemplate:
      "# The pantry already has a jar called rice and a jar called delivery.\n# The amounts are different every day!\nrice = [[]]\nprint(\"Rice jar now holds\", rice, \"scoops\")",
    customers: [
      { name: "Day 1", globals: { rice: 5, delivery: 3 },
        expect: [{ type: "var", name: "rice", equals: 8, pyType: "int" }, { type: "output", lines: ["Rice jar now holds 8 scoops"] }] },
      { name: "Day 2", globals: { rice: 2, delivery: 9 },
        expect: [{ type: "var", name: "rice", equals: 11, pyType: "int" }, { type: "output", lines: ["Rice jar now holds 11 scoops"] }] },
      { name: "Day 3", globals: { rice: 12, delivery: 4 },
        expect: [{ type: "var", name: "rice", equals: 16, pyType: "int" }, { type: "output", lines: ["Rice jar now holds 16 scoops"] }] },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "Python works out the right side of = first, using what's in the jars right now. Only then does it put the result into the jar on the left.",
      "A jar's own name can appear on the right side. Python uses the old amount there.",
      "Your step needs both jars on the right side, joined by an arithmetic sign. Never type today's numbers yourself.",
    ],
    successText: "Rice refilled correctly three days in a row",
  },
  {
    id: "1.5",
    chapter: 1,
    title: "Tea Time",
    concept: "Sequence",
    points: 20,
    scene: "pantry",
    mode: "reorder",
    story:
      "Asha wants a hot cup of tea. Pyu's tea recipe cards fell on the floor and got shuffled. Pyu will follow the cards in whatever order you put them, even if that order is wrong.",
    goal: "Drag the recipe steps into an order that serves Asha a **hot** cup of tea **with tea leaves** in it.",
    notes: ["Use the handles to drag, or the ▲ ▼ buttons to move a step."],
    reorderLines: [
      "cup = kettle",
      "kettle = \"cold water\"",
      "print(\"Serving:\", cup)",
      "kettle = \"hot water\"",
      "cup = cup + \" + tea leaves\"",
    ],
    bindings: [
      { object: "kettle", variable: "kettle" },
      { object: "teaCup", variable: "cup" },
    ],
    customers: [{ name: "Asha", says: "One hot tea, please!" }],
    checks: [
      { type: "noError" },
      { type: "var", name: "cup", equals: "hot water + tea leaves", pyType: "str",
        whenValue: [
          { value: "cold water + tea leaves", message: "The customer got cold tea. Pyu poured the water before it boiled. Look at the order of your steps." },
          { value: "hot water", message: "Asha got a cup of plain hot water. The tea leaves never made it into her cup." },
          { value: "cold water", message: "Asha got a cup of cold, plain water. Nothing was boiled and no leaves were added." },
          { value: "hot water + tea leaves + tea leaves", message: "Asha's tea has a double helping of tea leaves. How did that happen?" },
        ] },
      { type: "output", lines: ["Serving: hot water + tea leaves"],
        fail: "The tea was fine, but Pyu announced it at the wrong moment. Serving should happen when the tea is completely ready." },
    ],
    hints: [
      "Pyu does exactly one card at a time, from top to bottom. A card can only use a jar that already exists.",
      "When cup = kettle runs, the cup gets whatever is in the kettle at that moment. Changing the kettle later doesn't change the cup.",
      "Ask yourself what should be in the kettle at the moment Pyu pours it into the cup.",
    ],
    successText: "A steaming cup of tea served to Asha",
  },
];

// ============================================================ CHAPTER 2 — WHAT'S IN THE JAR (Data types)

export const CH2: Level[] = [
  {
    id: "2.1",
    chapter: 2,
    title: "Four Kinds of Jars",
    concept: "int, float, str, bool",
    points: 25,
    scene: "pantry",
    runLabel: "Day",
    story:
      "Some jars hold whole items like eggs, some hold a measured amount, some hold a written label, and some are just a light switch. Python has a different kind (type) of value for each.",
    goal: "Stock the shelf with four kinds of jar: `eggs` holding the whole number **12**, `sugar` holding **2.5** cups, `dish` holding the text **soup**, and `oven_on` holding the yes/no value for *the oven is on*.",
    notes: ["Watch how each jar looks different depending on what kind of thing is inside."],
    starterCode: "# Four jars, four different kinds of thing.\n\n",
    bindings: [{ object: "oven", variable: "oven_on" }],
    customers: [{ name: "Day 1" }],
    checks: [
      { type: "noError" },
      { type: "var", name: "eggs", equals: 12, pyType: "int",
        whenValue: [{ value: "12", message: "The eggs jar holds the text \"12\". Numbers shouldn't be wrapped in quotes." }] },
      { type: "var", name: "sugar", equals: 2.5, pyType: "float",
        whenValue: [{ value: "2.5", message: "The sugar jar holds the text \"2.5\". A decimal number shouldn't be wrapped in quotes." }] },
      { type: "var", name: "dish", equals: "soup", pyType: "str" },
      { type: "var", name: "oven_on", equals: true, pyType: "bool" },
    ],
    hints: [
      "Python has different kinds of values: whole numbers (int), decimal numbers (float), text (str) and True/False (bool).",
      "A decimal number is written with a dot, like 0.75. Don't put quotes around numbers.",
      "Only the dish needs quotes. The oven jar needs one of Python's two yes/no values.",
    ],
    successText: "Four different kinds of jar on the shelf",
  },
  {
    id: "2.2",
    chapter: 2,
    title: "Inspector Pyu",
    concept: "type()",
    points: 25,
    scene: "pantry",
    runLabel: "Day",
    story:
      "Four mystery jars arrived with no description. What's inside them changes every day, so Pyu can't just guess. He needs a proper inspection report.",
    goal: "Four mystery jars are on the shelf: `jar_a`, `jar_b`, `jar_c` and `jar_d`. Print the **type** of each jar, one per line, in the order a, b, c, d. Pyu wants Python's own description of each type, for example `<class 'int'>`.",
    mysteryVars: ["jar_a", "jar_b", "jar_c", "jar_d"],
    starterCode:
      "# The mystery jars jar_a, jar_b, jar_c and jar_d are already on the shelf.\n# Their contents change every day.\n\n",
    customers: [
      { name: "Day 1", globals: { jar_a: 7, jar_b: "7", jar_c: 7.5, jar_d: false },
        expect: [{ type: "output", lines: ["<class 'int'>", "<class 'str'>", "<class 'float'>", "<class 'bool'>"] }] },
      { name: "Day 2", globals: { jar_a: "hello", jar_b: true, jar_c: 3, jar_d: 0.25 },
        expect: [{ type: "output", lines: ["<class 'str'>", "<class 'bool'>", "<class 'int'>", "<class 'float'>"] }] },
      { name: "Day 3", globals: { jar_a: 9.75, jar_b: 40, jar_c: "True", jar_d: true },
        expect: [{ type: "output", lines: ["<class 'float'>", "<class 'int'>", "<class 'str'>", "<class 'bool'>"] }] },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "Python has a built-in tool that tells you the type of any value. Its name is exactly the word you're looking for.",
      "You can put one tool inside another. The result of the type tool can go straight into print.",
      "You need four report lines, one for each jar, in the order a, b, c, d.",
    ],
    successText: "Mystery jars identified three days running",
  },
  {
    id: "2.3",
    chapter: 2,
    title: "The Quoted Number",
    concept: "str vs int",
    points: 25,
    scene: "pantry",
    runLabel: "Day",
    story:
      "Pyu wrote the number of eggs with quote marks around it. To Python, \"5\" is a written label, not five eggs, so the recipe falls apart when Pyu tries to add.",
    goal: "Fix the recipe so the `eggs` jar holds a **real whole number** and Pyu announces the correct total of eggs.",
    starterCode:
      "eggs = \"5\"\nmore_eggs = 3\ntotal_eggs = eggs + more_eggs\nprint(\"Total eggs:\", total_eggs)\n",
    customers: [{ name: "Day 1" }],
    checks: [
      { type: "noError" },
      { type: "var", name: "eggs", equals: 5, pyType: "int",
        whenValue: [{ value: "5", message: "The eggs jar still holds the text \"5\". Pyu needs it to hold a real number." }] },
      { type: "var", name: "total_eggs", equals: 8, pyType: "int" },
      { type: "output", lines: ["Total eggs: 8"] },
    ],
    hints: [
      "Cook it and read the TypeError. Which two kinds of things is Python being asked to add together?",
      "\"5\" and 5 look alike, but one is text and one is a number. Compare the jars on the shelf.",
      "Only one line needs to change, and you only need to remove something from it.",
    ],
    successText: "Eggs counted correctly",
  },
  {
    id: "2.4",
    chapter: 2,
    title: "Convert It",
    concept: "int(), float(), str()",
    points: 25,
    scene: "pantry",
    runLabel: "Day",
    mode: "fill",
    story:
      "The order slips arrive all mixed up: numbers written as text, and text that should be numbers. Pyu needs each value turned into the right kind before he can use it.",
    goal: "Make three new jars from the old ones: `plates` must be the **whole number** version of `order`, `table_label` must be the **text** version of `table`, and `cups_needed` must be the **decimal number** version of `cups`.",
    notes: ["The jars order, table and cups change every day, so use them, not today's values."],
    fillTemplate:
      "# Jars already on the shelf (they change daily):\n#   order - number of plates, written as text, e.g. \"3\"\n#   table - the table number, a whole number, e.g. 4\n#   cups  - cups of milk, written as text, e.g. \"2.5\"\nplates = [[]]\ntable_label = [[]]\ncups_needed = [[]]\nprint(plates + 1, \"Table \" + table_label, cups_needed * 2)",
    bindings: [{ object: "plates", variable: "plates" }],
    customers: [
      { name: "Day 1", globals: { order: "3", table: 4, cups: "2.5" },
        expect: [
          { type: "var", name: "plates", equals: 3, pyType: "int" },
          { type: "var", name: "table_label", equals: "4", pyType: "str" },
          { type: "var", name: "cups_needed", equals: 2.5, pyType: "float" },
        ] },
      { name: "Day 2", globals: { order: "7", table: 12, cups: "0.5" },
        expect: [
          { type: "var", name: "plates", equals: 7, pyType: "int" },
          { type: "var", name: "table_label", equals: "12", pyType: "str" },
          { type: "var", name: "cups_needed", equals: 0.5, pyType: "float" },
        ] },
      { name: "Day 3", globals: { order: "1", table: 9, cups: "4.0" },
        expect: [
          { type: "var", name: "plates", equals: 1, pyType: "int" },
          { type: "var", name: "table_label", equals: "9", pyType: "str" },
          { type: "var", name: "cups_needed", equals: 4, pyType: "float" },
        ] },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "Python has converters named after the types: one for whole numbers, one for decimals and one for text.",
      "A converter takes a value inside round brackets and hands back a new value of its own type.",
      "Put the existing jar names inside the converters. Never type today's numbers yourself, because they change every day.",
    ],
    successText: "Every order slip converted",
  },
];

// ============================================================ CHAPTER 3 — THE SCALES COUNTER (Operators)

export const CH3: Level[] = [
  {
    id: "3.1",
    chapter: 3,
    title: "Weigh It Up",
    concept: "+ - * /",
    points: 15,
    scene: "scales",
    runLabel: "Day",
    story: "The baking order has arrived. Pyu needs the numbers worked out before he starts measuring.",
    goal: "The jars `flour`, `sugar` and `butter` hold today's amounts in grams. Make four jars:\n- `total`: the weight of all three together\n- `extra_flour`: how many more grams of flour there are than butter\n- `per_cake`: the total shared equally between **4** cakes\n- `triple_sugar`: the sugar needed for a triple batch",
    starterCode: "# Jars already on the shelf (grams): flour, sugar, butter\n# The amounts change every day.\n\n",
    bindings: [{ object: "scale", variable: "total", label: "total" }],
    customers: [
      { name: "Day 1", globals: { flour: 500, sugar: 200, butter: 100 },
        expect: [
          { type: "var", name: "total", equals: 800, pyType: "number" },
          { type: "var", name: "extra_flour", equals: 400, pyType: "number" },
          { type: "var", name: "per_cake", equals: 200, pyType: "number" },
          { type: "var", name: "triple_sugar", equals: 600, pyType: "number" },
        ] },
      { name: "Day 2", globals: { flour: 300, sugar: 150, butter: 50 },
        expect: [
          { type: "var", name: "total", equals: 500, pyType: "number" },
          { type: "var", name: "extra_flour", equals: 250, pyType: "number" },
          { type: "var", name: "per_cake", equals: 125, pyType: "number" },
          { type: "var", name: "triple_sugar", equals: 450, pyType: "number" },
        ] },
      { name: "Day 3", globals: { flour: 250, sugar: 120, butter: 75 },
        expect: [
          { type: "var", name: "total", equals: 445, pyType: "number" },
          { type: "var", name: "extra_flour", equals: 175, pyType: "number" },
          { type: "var", name: "per_cake", equals: 111.25, pyType: "number" },
          { type: "var", name: "triple_sugar", equals: 360, pyType: "number" },
        ] },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "Python's arithmetic signs: + adds, - subtracts, * multiplies and / divides.",
      "A calculation can use any jar, including a jar you made on an earlier line.",
      "per_cake shares the total, so it depends on a jar you should already have made.",
    ],
    successText: "Ingredients weighed for three days",
  },
  {
    id: "3.2",
    chapter: 3,
    title: "Cookie Boxes",
    concept: "// and %",
    points: 15,
    scene: "scales",
    runLabel: "Day",
    story: "The cookie shop only sells full boxes. Pyu needs to know how many full boxes he can pack, and how many cookies he gets to eat.",
    goal: "Pyu packs `cookies` into boxes that each hold `box_size` cookies (both jars change daily). Make `full_boxes`, how many boxes can be **completely** filled, and `left_over`, how many cookies are left that don't fill a box.",
    starterCode: "# Jars already on the shelf: cookies and box_size\n\n",
    bindings: [{ object: "cookieBox", variable: "full_boxes", extra: "left_over" }],
    customers: [
      { name: "Day 1", globals: { cookies: 17, box_size: 5 },
        expect: [{ type: "var", name: "full_boxes", equals: 3, pyType: "int" }, { type: "var", name: "left_over", equals: 2, pyType: "int" }] },
      { name: "Day 2", globals: { cookies: 24, box_size: 6 },
        expect: [{ type: "var", name: "full_boxes", equals: 4, pyType: "int" }, { type: "var", name: "left_over", equals: 0, pyType: "int" }] },
      { name: "Day 3", globals: { cookies: 10, box_size: 3 },
        expect: [{ type: "var", name: "full_boxes", equals: 3, pyType: "int" }, { type: "var", name: "left_over", equals: 1, pyType: "int" }] },
      { name: "Day 4", globals: { cookies: 4, box_size: 5 },
        expect: [{ type: "var", name: "full_boxes", equals: 0, pyType: "int" }, { type: "var", name: "left_over", equals: 4, pyType: "int" }] },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "Normal division gives 3.4 for 17 ÷ 5, but you can't have 0.4 of a full box.",
      "Python has a division that throws away the remainder, and a separate operator that gives only the remainder.",
      "Look up // and % in Python. Try them on 17 and 5 and see what comes out.",
    ],
    successText: "Cookies boxed for four days",
  },
  {
    id: "3.3",
    chapter: 3,
    title: "Double Batch",
    concept: "+=, -=, *=",
    points: 15,
    scene: "scales",
    runLabel: "Day",
    story: "The customers loved yesterday's cake, so Pyu is making a double batch. It's a healthier version too.",
    goal: "Update the existing jars. Don't make new ones:\n- **double** the `flour`\n- add **2** more `eggs`\n- take **30** grams away from `sugar`\n\nThen print `Batch ready!`",
    starterCode: "# Jars already on the shelf: flour (grams), eggs, sugar (grams)\n\n",
    bindings: [{ object: "scale", variable: "flour", label: "flour" }],
    customers: [
      { name: "Day 1", globals: { flour: 200, eggs: 3, sugar: 100 },
        expect: [
          { type: "var", name: "flour", equals: 400, pyType: "int" },
          { type: "var", name: "eggs", equals: 5, pyType: "int" },
          { type: "var", name: "sugar", equals: 70, pyType: "int" },
        ] },
      { name: "Day 2", globals: { flour: 350, eggs: 1, sugar: 90 },
        expect: [
          { type: "var", name: "flour", equals: 700, pyType: "int" },
          { type: "var", name: "eggs", equals: 3, pyType: "int" },
          { type: "var", name: "sugar", equals: 60, pyType: "int" },
        ] },
      { name: "Day 3", globals: { flour: 120, eggs: 6, sugar: 30 },
        expect: [
          { type: "var", name: "flour", equals: 240, pyType: "int" },
          { type: "var", name: "eggs", equals: 8, pyType: "int" },
          { type: "var", name: "sugar", equals: 0, pyType: "int" },
        ] },
    ],
    checks: [{ type: "noError" }, { type: "output", lines: ["Batch ready!"] }],
    hints: [
      "Updating a jar means using its old value to make its new value.",
      "Python has shortcuts that update a jar in place: +=, -= and *=.",
      "Each ingredient needs its own update step.",
    ],
    successText: "Double batches ready three days running",
  },
  {
    id: "3.4",
    chapter: 3,
    title: "Taste Thermometer",
    concept: "Comparison operators",
    points: 20,
    scene: "scales",
    runLabel: "Day",
    story: "Pyu's thermometer reads the soup's temperature, but Pyu wants straight yes/no answers, not numbers.",
    goal: "Make four True/False jars about today's `temperature` (it changes every day):\n- `hot_enough`: is it **at least** 75?\n- `perfect`: is it **exactly** 80?\n- `too_hot`: is it **more than** 90?\n- `not_cold`: is it **anything other than** 20?",
    starterCode: "# The jar temperature is already on the shelf.\n\n",
    bindings: [{ object: "thermometer", variable: "temperature" }],
    customers: [
      { name: "Day 1", globals: { temperature: 80 }, expect: boolChecks(true, true, false, true) },
      { name: "Day 2", globals: { temperature: 60 }, expect: boolChecks(false, false, false, true) },
      { name: "Day 3", globals: { temperature: 95 }, expect: boolChecks(true, false, true, true) },
      { name: "Day 4", globals: { temperature: 20 }, expect: boolChecks(false, false, false, false) },
      { name: "Day 5", hidden: true, globals: { temperature: 75 }, expect: boolChecks(true, false, false, true) },
      { name: "Day 6", hidden: true, globals: { temperature: 90 }, expect: boolChecks(true, false, false, true) },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "A comparison like 3 > 2 is a question, and Python answers it with True or False. You can store that answer in a jar.",
      "\"At least\" means greater than or equal to. Careful: a single = means \"put in the jar\", but a double == asks \"are these equal?\"",
      "Python writes \"not equal to\" as !=.",
    ],
    successText: "The thermometer answers every question correctly",
  },
  {
    id: "3.5",
    chapter: 3,
    title: "Ready to Bake?",
    concept: "and, or, not",
    points: 20,
    scene: "scales",
    runLabel: "Day",
    story: "Pyu once put a tray into a cold oven. Never again! Now he wants the oven to tell him when it's really ready.",
    goal: "Use the jars `preheated`, `tray_in` and `baking` (all True/False, and they change daily):\n- `oven_ready` must be True only when the oven is preheated **and** the tray is in **and** it is **not** already baking.\n- `need_help` must be True when the oven is **not** preheated **or** the tray is **not** in.",
    starterCode: "# Jars already on the shelf: preheated, tray_in, baking\n\n",
    bindings: [{ object: "oven", variable: "oven_ready" }],
    customers: [
      { name: "Day 1", globals: { preheated: true, tray_in: true, baking: false }, expect: ovenChecks(true, false) },
      { name: "Day 2", globals: { preheated: true, tray_in: true, baking: true }, expect: ovenChecks(false, false) },
      { name: "Day 3", globals: { preheated: false, tray_in: true, baking: false }, expect: ovenChecks(false, true) },
      { name: "Day 4", globals: { preheated: true, tray_in: false, baking: false }, expect: ovenChecks(false, true) },
      { name: "Day 5", hidden: true, globals: { preheated: false, tray_in: false, baking: true }, expect: ovenChecks(false, true) },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "Python joins True/False questions together with the words and, or and not.",
      "and is True only when both sides are True. or is True when at least one side is True. not flips True and False.",
      "You can chain more than two jars together with and. Put not in front of a single jar to flip it.",
    ],
    successText: "The oven knows exactly when it's ready",
  },
  {
    id: "3.6",
    chapter: 3,
    title: "Check the Fridge",
    concept: "in, not in",
    points: 15,
    scene: "scales",
    runLabel: "Day",
    story: "Before starting an omelette, Pyu checks what's in the fridge.",
    goal: "The `fridge` jar holds a list of what's inside (it changes daily). Make `has_egg`, which is True if `\"egg\"` is in the fridge, and `no_milk`, which is True if `\"milk\"` is **not** in the fridge.",
    starterCode: "# The jar fridge is already on the shelf, e.g. [\"egg\", \"butter\"]\n\n",
    bindings: [{ object: "fridge", variable: "fridge" }],
    customers: [
      { name: "Day 1", globals: { fridge: ["egg", "butter", "milk"] }, expect: fridgeChecks(true, false) },
      { name: "Day 2", globals: { fridge: ["cheese", "milk"] }, expect: fridgeChecks(false, false) },
      { name: "Day 3", globals: { fridge: ["egg", "jam"] }, expect: fridgeChecks(true, true) },
      { name: "Day 4", globals: { fridge: [] }, expect: fridgeChecks(false, true) },
    ],
    checks: [{ type: "noError" }],
    hints: [
      "Python can check whether something is inside a list with one short word.",
      "That word is in, and there's a two-word version that means the opposite.",
      "The thing you're looking for is text, so it needs quotes.",
    ],
    successText: "The fridge checked four days in a row",
  },
];

function boolChecks(hot: boolean, perfect: boolean, tooHot: boolean, notCold: boolean) {
  return [
    { type: "var" as const, name: "hot_enough", equals: hot, pyType: "bool" as const },
    { type: "var" as const, name: "perfect", equals: perfect, pyType: "bool" as const },
    { type: "var" as const, name: "too_hot", equals: tooHot, pyType: "bool" as const },
    { type: "var" as const, name: "not_cold", equals: notCold, pyType: "bool" as const },
  ];
}

function ovenChecks(ready: boolean, help: boolean) {
  return [
    { type: "var" as const, name: "oven_ready", equals: ready, pyType: "bool" as const },
    { type: "var" as const, name: "need_help", equals: help, pyType: "bool" as const },
  ];
}

function fridgeChecks(egg: boolean, noMilk: boolean) {
  return [
    { type: "var" as const, name: "has_egg", equals: egg, pyType: "bool" as const },
    { type: "var" as const, name: "no_milk", equals: noMilk, pyType: "bool" as const },
  ];
}
