// Reference solutions used ONLY by scripts/verify-levels.ts.
// This folder is never imported by the app, so answers never ship to students.

export type Work = { code?: string; fill?: string[]; order?: number[] };

export const SOLUTIONS: Record<string, Work> = {
  "1.1": { code: `rice = 5\nname = "Pyu"\n` },
  "1.2": { code: `eggs = 6\nsugar = 2\nchef = "Pyu"\noven_on = True\n` },
  "1.3": { code: `eggs2 = 12\nmy_rice = 5\nchef_name = "Pyu"\nprint("Pantry labels fixed!")\n` },
  "1.4": { fill: ["rice + delivery"] },
  "1.5": { order: [1, 3, 0, 4, 2] },
  "2.1": { code: `eggs = 12\nsugar = 2.5\ndish = "soup"\noven_on = True\n` },
  "2.2": { code: `print(type(jar_a))\nprint(type(jar_b))\nprint(type(jar_c))\nprint(type(jar_d))\n` },
  "2.3": { code: `eggs = 5\nmore_eggs = 3\ntotal_eggs = eggs + more_eggs\nprint("Total eggs:", total_eggs)\n` },
  "2.4": { fill: ["int(order)", "str(table)", "float(cups)"] },
  "3.1": { code: `total = flour + sugar + butter\nextra_flour = flour - butter\nper_cake = total / 4\ntriple_sugar = sugar * 3\n` },
  "3.2": { code: `full_boxes = cookies // box_size\nleft_over = cookies % box_size\n` },
  "3.3": { code: `flour *= 2\neggs += 2\nsugar -= 30\nprint("Batch ready!")\n` },
  "3.4": { code: `hot_enough = temperature >= 75\nperfect = temperature == 80\ntoo_hot = temperature > 90\nnot_cold = temperature != 20\n` },
  "3.5": { code: `oven_ready = preheated and tray_in and not baking\nneed_help = not preheated or not tray_in\n` },
  "3.6": { code: `has_egg = "egg" in fridge\nno_milk = "milk" not in fridge\n` },
  "4.1": { code: `print("Welcome to Pyu's Kitchen!")\nprint("Dish of the day: Masala Dosa")\n` },
  "4.2": { code: `name = input("What's your name? ")\nprint(f"Welcome, {name}!")\n` },
  "4.3": { code: `name = input()\nplates = input()\ndish = input()\nprint(f"Order for {name}: {plates} x {dish}")\n` },
  "4.4": { code: `price = 80\nplates = int(input("How many plates? "))\nbill = price * plates\nprint("Bill:", bill)\n` },
  "5.1": { code: `if salt > 5:\n    water += 2\n    print("Added water")\n` },
  "5.2": { code: `if salt > 5:\n    water = water + 2\n    print("Too salty! Adding water")\nelse:\n    print("Tasty! Serving soup")\n` },
  "5.3": { code: `if spice <= 3:\n    label = "mild"\nelif spice <= 6:\n    label = "medium"\nelif spice <= 9:\n    label = "hot"\nelse:\n    label = "dangerous"\nprint("Spice label:", label)\n` },
  "5.4": { code: `total = price * quantity\nif is_member and quantity >= 5:\n    total = total * 0.8\nelif is_member or quantity >= 10:\n    total = total * 0.9\nprint("Total:", total)\n` },
  "5.5": { code: `if dish == "satay":\n    if allergy == "peanuts":\n        print("Sorry, satay has peanuts")\n    else:\n        print("Serving satay")\nelse:\n    print("Serving", dish)\n` },
  "6.1": { code: `stirs = 0\nfor i in range(10):\n    stirs = stirs + 1\nprint("Stirred", stirs, "times")\n` },
  "6.2": { code: `for dish in orders:\n    print("Ticket:", dish)\nprint("All plated!")\n` },
  "6.3": { code: `while temperature < 100:\n    temperature += 20\nprint("Soup is ready at", temperature)\n` },
  "6.4": { code: `for r in range(1, rows + 1):\n    for s in range(1, spots + 1):\n        print(f"Cookie at row {r}, spot {s}")\n` },
  "6.5": { code: `for item in fridge:\n    print("Checking", item)\n    if item == "butter":\n        print("Found the butter!")\n        break\n` },
  "6.6": { code: `packed = 0\nfor cookie in cookies:\n    if cookie == "burnt":\n        continue\n    print(f"Packed a {cookie} cookie")\n    packed += 1\nprint(f"Packed {packed} cookies")\n` },
  "7.1": { code: `def make_tea():\n    print("Here is your tea!")\n\nmake_tea()\nmake_tea()\nmake_tea()\n` },
  "7.2": { code: `def make_juice(fruit):\n    print(f"One {fruit} juice, coming up!")\n\nmake_juice("mango")\nmake_juice("apple")\nmake_juice("orange")\n` },
  "7.3": { code: `def calculate_bill(price, quantity):\n    return price * quantity\n\nprint(calculate_bill(80, 3))\n` },
  "7.4": { code: `def make_coffee(size="medium"):\n    return f"A {size} coffee"\n\nprint(make_coffee())\nprint(make_coffee("small"))\n` },
  "7.5": { code: `def add_toppings(dish):\n    topped = dish + " with cheese"\n    return topped\n\ntopped = add_toppings("pasta")\nprint("Serving:", topped)\n` },
  "7.6": { code: `def calculate_bill(price, quantity, is_member):\n    cost = price * quantity\n    if is_member:\n        cost = cost * 0.9\n    if cost > 500:\n        cost = cost - 50\n    return cost\n\nprint(calculate_bill(100, 3, True))\n` },
  "8.1": { code: `dish = "soup"\ntemperature = 90\nif temperature > 80:\n    print("The", dish, "is hot")\nservings = (2 + 3)\nprint("Serve", servings, "bowls of", dish)\n` },
  "8.2": { code: `sugar = 3\nflour = 250\nmilk = 2\nprint("Sugar:", sugar)\ntotal_cups = sugar + milk\nprint("Flour:", flour)\nprint("Cups of stuff:", total_cups)\n` },
  "8.3": { code: `plates = 4\nprice = 50\nbill = plates * price\nprint("Plates:", plates)\nprint("Bill: " + str(bill))\nextra = 20\nnew_bill = bill + extra\nprint("New bill:", new_bill)\n` },
  "8.4": { code: `price = 40\nplates = int(input())\nbill = price * plates\nif plates >= 5:\n    bill = bill - 10\nprint("Bill:", bill)\n` },
  "8.5": { code: `def portion_size(total_grams, people):\n    return total_grams / people\n\nrice_grams = 900\npeople = int(input())\nsize = portion_size(rice_grams, people)\nprint("Each person gets", size, "grams")\n` },
  "8.6": { code: `def total_cost(price, plates):\n    return price * plates\n\nprice = 60\nplates = int(input())\nbill = total_cost(price, plates)\nif bill > 200:\n    print("Big order! Bill:", bill)\nelse:\n    print("Bill:", bill)\n` },
  "9.1": { code: `total = 0\nnumber = 1\nfor price in orders:\n    print(f"Order {number}: {price}")\n    total += price\n    number += 1\nprint("Total earned:", total)\n` },
  "9.2": { code: `menu = {"dosa": 80, "noodles": 120, "satay": 150}\ndish = input()\nplates = int(input())\nmember = input()\nallergy = input()\nif dish == "satay" and allergy == "peanuts":\n    print("Sorry, satay contains peanuts")\nelse:\n    bill = menu[dish] * plates\n    if member == "yes":\n        bill = bill * 0.9\n    if plates >= 5:\n        bill = bill - 50\n    print(f"Serving {plates} x {dish}. Bill: {bill}")\n` },
  "9.3": { code: `def price_of(dish):\n    if dish == "dosa":\n        return 80\n    elif dish == "idli":\n        return 50\n    elif dish == "vada":\n        return 40\n    elif dish == "chai":\n        return 20\n    return None\n\nname = input()\ncount = int(input())\nprint("Receipt for", name)\nsubtotal = 0\nfor i in range(count):\n    dish = input()\n    price = price_of(dish)\n    if price is None:\n        print("Not on the menu:", dish)\n    else:\n        print(f"{dish}: {price}")\n        subtotal += price\nmember = input()\ndiscount = 0\nif member == "yes":\n    discount = subtotal * 0.1\nif subtotal >= 300:\n    discount += 25\nprint("Subtotal:", subtotal)\nprint("Discount:", round(discount, 2))\nprint("Total:", round(subtotal - discount, 2))\n` },
};

// Plausible wrong attempts, with a fragment the failure message must contain.
export const MISTAKES: { id: string; work: Work; expect: string }[] = [
  { id: "1.1", work: { code: `rice = "5"\nname = "Pyu"\n` }, expect: "quotes" },
  { id: "1.1", work: { code: `Rice = 5\nname = "Pyu"\n` }, expect: "no jar called \"rice\"" },
  { id: "1.4", work: { fill: ["8"] }, expect: "Day 2" },
  { id: "1.5", work: { order: [1, 0, 3, 4, 2] }, expect: "cold tea" },
  { id: "1.5", work: { order: [0, 1, 2, 3, 4] }, expect: "kettle" },
  { id: "2.3", work: { code: `eggs = "5"\nmore_eggs = 3\ntotal_eggs = eggs + str(more_eggs)\nprint("Total eggs:", total_eggs)\n` }, expect: "still holds the text" },
  { id: "3.1", work: { code: `total = flour + sugar + butter\nextra_flour = flour - butter\nper_cake = total // 4\ntriple_sugar = sugar * 3\n` }, expect: "Day 3" },
  { id: "4.4", work: { code: `price = 80\nplates = input()\nprint("Bill:", price * plates)\n` }, expect: "Asha ordered 3 plates" },
  { id: "4.4", work: { code: `plates = input()\nplates2 = input()\n` }, expect: "twice" },
  { id: "5.2", work: { code: `if salt >= 5:\n    water += 2\n    print("Too salty! Adding water")\nelse:\n    print("Tasty! Serving soup")\n` }, expect: "Mei" },
  { id: "6.1", work: { code: `stirs = 10\nprint("Stirred", stirs, "times")\n` }, expect: "one stir at a time" },
  { id: "6.1", work: { code: "stirs = 0\n" + "stirs = stirs + 1\n".repeat(10) + `print("Stirred", stirs, "times")\n` }, expect: "4 lines or fewer" },
  { id: "6.3", work: { code: `while temperature < 100:\n    temperature + 20\nprint("Soup is ready at", temperature)\n` }, expect: "stirring forever" },
  { id: "6.3", work: { code: `while temperature < 100:\n    print("heating")\n` }, expect: "printer jammed" },
  { id: "6.3", work: { code: `for i in range(4):\n    temperature += 20\nprint("Soup is ready at", temperature)\n` }, expect: "Day 3" },
  { id: "1.3", work: { code: `eggs2 = 12\nmy_rice = 5\nclass = "Pyu"\nprint("Pantry labels fixed!")\n` }, expect: "keeps for itself" },
  { id: "2.2", work: { code: `print("<class 'int'>")\nprint("<class 'str'>")\nprint("<class 'float'>")\nprint("<class 'bool'>")\n` }, expect: "Day 2" },
  { id: "4.2", work: { code: `name = input()\nname2 = input()\n` }, expect: "twice" },
  { id: "8.5", work: {}, expect: "text" },
  { id: "9.3", work: { code: `import math\n` }, expect: "doesn't stock" },
  { id: "7.3", work: { code: `def calculate_bill(price, quantity):\n    print(price * quantity)\n\ncalculate_bill(80, 3)\n` }, expect: "returned" },
  { id: "7.5", work: { code: `def add_toppings(dish):\n    topped = dish + " with cheese"\n    return topped\n\nprint("Serving:", "pasta with cheese")\n` }, expect: "never used" },
  { id: "8.2", work: {}, expect: "Did you mean \"sugar\"" },
  { id: "8.6", work: {}, expect: "colon" },
  { id: "9.1", work: { code: `for p in orders:\n    print("Order 1:", p)\n` }, expect: "Order 2" },
];
